export const SHOW_BUTTON_LOGIN = "SHOW_BUTTON_LOGIN";

export const LOAD_SELECTED_DATA = "LOAD_SELECTED_DATA";
export const LOAD_ANIME_LIST = "LOAD_ANIME_LIST";

export const LOAD_USER_ENTITY_SELECTED = "LOAD_USER_ENTITY_SELECTED"
export const LOAD_USER_ENTITY_LIST = "LOAD_USER_ENTITY_LIST";

export const LOAD_ACCESS_PROFILE_SELECTED = "LOAD_ACCESS_PROFILE_SELECTED";
export const LOAD_ACCESS_PROFILE_LIST = "LOAD_ACCESS_PROFILE_LIST"
